export enum EntityType {
  BOT_COMMAND = 'bot_command',
  MENTION = 'mention',
  HASHTAG = 'hashtag',
  CASHTAG = 'cashtag',
  URL = 'url',
  EMAIL = 'email',
  PHONE_NUMBER = 'phone_number',
  BOLD = 'bold',
  ITALIC = 'italic',
  UNDERLINE = 'underline',
  CODE = 'code',
  STRIKETHROUGH = 'strikethrough',
  SPOILER = 'spoiler',
  TEXT_LINK = 'text_link',
  TEXT_MENTION = 'text_mention',
  CUSTOM_EMOJI = 'custom_emoji',
}
